# Generated by Django 5.1.4 on 2024-12-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
